{
 "title": "Daemonit Stats",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "Data Source", "query": "grafana-timestream-datasource" },
   {
    "name": "monitoring_uuid",
    "label": "Monitoring UUID",
    "query": "SELECT DISTINCT(monitoring_uuid) FROM \"$__database\".\"$__table\""
   },
   { "name": "device", "label": "Device", "query": "desktop,mobile" },
   {
    "name": "url",
    "label": "URL",
    "query": "SELECT DISTINCT(url) FROM \"$__database\".\"$__table\""
   }
  ]
 },
 "panels": [
  { "title": "Monitoring List", "type": "table", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Current Score",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::double\nFROM \"$__database\".\"$__table\"\nWHERE $__timeFilter\nAND measure_name = 'scoreTotal'\nAND device_type = '${device}'\nAND monitoring_uuid = '${monitoring_uuid}'"
    }
   ]
  },
  {
   "title": "Current Server Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawQuery": "SELECT \n    REPLACE(measure_name, 'metric', '') as display_measure_name,\n    CREATE_TIME_SERIES(time, measure_value::double)\nFROM \"$__database\".\"$__table\"\nWHERE $__timeFilter AND measure_name = 'metricServerResponseTime' AND monitoring_uuid = '${monitoring_uuid}' AND device_type = '${device}'\nGROUP BY measure_name"
    }
   ]
  },
  {
   "title": "Latest Data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawQuery": "SELECT MAX(time)\nFROM \"$__database\".\"$__table\"\nWHERE monitoring_uuid = '${monitoring_uuid}'"
    }
   ]
  },
  {
   "title": "Oldest Data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawQuery": "SELECT MIN(time)\nFROM \"$__database\".\"$__table\"\nWHERE monitoring_uuid = '${monitoring_uuid}'"
    }
   ]
  },
  {
   "title": "Worst Score",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::double\nFROM \"$__database\".\"$__table\"\nWHERE $__timeFilter\nAND measure_name = 'scoreTotal'\nAND device_type = '${device}'\nAND monitoring_uuid = '${monitoring_uuid}'"
    }
   ]
  },
  {
   "title": "Max Server Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawQuery": "SELECT \n    REPLACE(measure_name, 'metric', '') as display_measure_name,\n    CREATE_TIME_SERIES(time, measure_value::double)\nFROM \"$__database\".\"$__table\"\nWHERE $__timeFilter AND measure_name = 'metricServerResponseTime' AND monitoring_uuid = '${monitoring_uuid}' AND device_type = '${device}'\nGROUP BY measure_name"
    }
   ]
  },
  {
   "title": "GDPR valid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawQuery": "SELECT \n    measure_name,\n    CREATE_TIME_SERIES(time, measure_value::double)\nFROM \"$__database\".\"$__table\"\nWHERE $__timeFilter AND measure_name = 'scoreGdpr' AND monitoring_uuid = '${monitoring_uuid}' AND device_type = '${device}'\nGROUP BY measure_name"
    }
   ]
  },
  {
   "title": "Mean SpeedIndex by device",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawQuery": "SELECT \n    device_type,\n    CREATE_TIME_SERIES(time, measure_value::double)\nFROM \"$__database\".\"$__table\"\nWHERE $__timeFilter AND measure_name = 'metricSpeedIndex' AND monitoring_uuid = '${monitoring_uuid}'\nGROUP BY measure_name, device_type\nORDER BY device_type"
    }
   ]
  },
  {
   "title": "Compare Score ${device}",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawQuery": "SELECT \n    url, engine_name,\n    CREATE_TIME_SERIES(time, measure_value::double)\nFROM \"$__database\".\"$__table\"\nWHERE $__timeFilter AND measure_name = 'scoreTotal' AND device_type = '${device}'\nGROUP BY url, engine_name"
    }
   ]
  },
  {
   "title": "Display Performance ${device}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT \n    REPLACE(measure_name, 'metric', '') as display_measure_name,\n    CREATE_TIME_SERIES(time, measure_value::double)\nFROM \"$__database\".\"$__table\"\nWHERE $__timeFilter AND measure_name IN ('metricInteractive', 'metricFirstCPUIdle', 'metricSpeedIndex', 'metricServerResponseTime') AND monitoring_uuid = '${monitoring_uuid}' AND device_type = '${device}'\nGROUP BY measure_name"
    }
   ]
  },
  {
   "title": "Score ${device}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "Score" }
   ],
   "targets": [
    {
     "measure": "metricInteractive",
     "rawQuery": "SELECT \n    REPLACE(REPLACE(REPLACE(measure_name, 'score', ''), 'Hosting', 'Hosting/Security'), 'BestPractices', 'Best practices') as display_measure_name,\n    CREATE_TIME_SERIES(time, measure_value::double)\nFROM \"$__database\".\"$__table\"\nWHERE $__timeFilter AND measure_name LIKE 'score%' AND monitoring_uuid = '${monitoring_uuid}' AND device_type = '${device}'\nGROUP BY measure_name"
    }
   ]
  }
 ]
}